spring:
  datasource:
    platform: POSTGRESQL
    url: "jdbc:postgresql://localhost:5432/testdb"
    username: postgres
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
api:
  root: /

server:
  port: 8094
endpoints:
  cors:
    allowed-headers: "Content-Type"

